# Generated by Django 5.1.6 on 2025-03-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_payment_order_id_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Esewa', max_length=20),
        ),
    ]
