# Generated by Django 5.1.6 on 2025-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_websitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_chef_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
