# Generated by Django 5.1.6 on 2025-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_chef_pick',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_screenshot',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash on Delivery'), ('E-Payment', 'E-Payment')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
