# Generated by Django 5.1.6 on 2025-04-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_fooditem_average_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
