# Generated by Django 5.1.6 on 2025-04-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
