# Generated by Django 5.1.6 on 2025-04-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('happy_guests', models.PositiveIntegerField(default=0)),
                ('dishes_served', models.PositiveIntegerField(default=0)),
                ('staff_members', models.PositiveIntegerField(default=0)),
                ('website_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
