# Generated by Django 5.1.6 on 2025-04-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_remove_dashboardstats_website_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstats',
            name='dishes_limit',
            field=models.PositiveIntegerField(default=10000, help_text='Limit for Dishes Served animation'),
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='guests_limit',
            field=models.PositiveIntegerField(default=2000, help_text='Limit for Happy Guests animation'),
        ),
    ]
