# Generated by Django 5.1.6 on 2025-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_dashboardstats_dishes_limit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
