# Generated by Django 5.1.6 on 2025-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_remove_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('size', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('bed', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dashboardstats',
            options={'verbose_name_plural': 'Dashboard Stats'},
        ),
    ]
