# Generated by Django 5.1.6 on 2025-04-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_roomcategory_room_number_room_category_roomorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
