# Generated by Django 5.1.6 on 2025-04-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_remove_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room_number',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='room_numbers',
            field=models.CharField(blank=True, help_text='Comma-separated list of room numbers', max_length=255, null=True),
        ),
    ]
