# Generated by Django 5.1.6 on 2025-04-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_remove_order_room_number_roomcategory_room_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='room_numbers',
            field=models.TextField(blank=True, help_text="Enter room numbers separated by commas (e.g., '101,102,103')", null=True),
        ),
    ]
