# Generated by Django 5.1.6 on 2025-04-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_alter_roomcategory_room_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
    ]
