# Generated by Django 5.1.6 on 2025-04-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_roomorder_room_number_alter_roomorder_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorder',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.room'),
        ),
    ]
