# Generated by Django 5.1.6 on 2025-04-30 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_alter_roomorder_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.roomcategory'),
        ),
    ]
