# Generated by Django 5.1.6 on 2025-04-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_roomorder_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomorder',
            name='room',
        ),
    ]
