# Generated by Django 5.1.6 on 2025-04-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_remove_cartitem_order_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
