# Generated by Django 5.1.6 on 2025-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_roomorder_is_paid_roomorder_payment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
