# Generated by Django 5.2.1 on 2025-05-17 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0037_roomorderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomorder',
            name='category',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='status',
        ),
        migrations.AddField(
            model_name='roomorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name of the person staying in the room', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.room'),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
