# Generated by Django 5.2.1 on 2025-05-17 06:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_remove_roomorder_category_remove_roomorder_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='roomorder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='roomorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.roomcategory'),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
