# Generated by Django 5.2.1 on 2025-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0039_remove_roomorder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
