# Generated by Django 5.2.1 on 2025-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0040_roomorder_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bill to company', 'Bill to company')], max_length=50, null=True),
        ),
    ]
