# Generated by Django 5.2.1 on 2025-05-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0041_roomorder_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name_plural': 'Room Categories'},
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
